<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;



/*                                                                        *
 * This script belongs to the TYPO3 Flow package "MH.Guestbook".          *
 *                                                                        *
 * It is free software; you can redistribute it and/or modify it under    *
 * the terms of the GNU Lesser General Public License, either version 3   *
 * of the License, or (at your option) any later version.                 *
 *                                                                        */



use Doctrine\DBAL\Migrations\AbstractMigration,
Doctrine\DBAL\Schema\Schema;



/**
 * Create guestbook entry table.
 */
class Version20121013172229 extends AbstractMigration
{



	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE mh_guestbook_domain_model_entry (persistence_object_identifier VARCHAR(40) NOT NULL, date DATETIME NOT NULL, author VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
	}



	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE mh_guestbook_domain_model_entry");
	}


}

